config/routes.rb
Rails.application.routes.draw do

  resources :roles
	constraints(Subdomain) do
		resources :pharmacies do
  		collection do
  			get 'search'
  		end
  	end
		devise_for :employees
		resources :employees
		resources :clients
		resources :suppliers
		resources :account_drugs
    resources :initial_balances
    resources :inventories
	end
	resources :drugs do
		collection do
			get 'search'
			get 'info'
      get 'alternatives'
		end
	end

	get 'home' => 'home#index'
	devise_for :accounts, :controllers => {:registrations => "accounts"}

	root 'home#index'

end

app/models/employee.rb
class Employee < CouchRest::Model::Base

	belongs_to :role
	proxied_by :account
	design do
		view :by_email
		view :by_account_id
		view :by_account_id_and_id,
		:map => "function(doc) {
          if (doc.account_id) {
            emit([doc._id,doc.account_id], 1)
          }
        }",
		:reduce => "_sum"
	end

	devise :database_authenticatable, request_keys: [:subdomain]
	def self.find_for_authentication(tainted_conditions)
		account = Account.by_subdomain.key(tainted_conditions[:subdomain]).limit(1).first
		account.employees.by_email.key(tainted_conditions[:email]).limit(1).first
	end
	def self.serialize_into_session(record)
		[record.to_key, record.authenticatable_salt, record.account_id]
	end
	def self.serialize_from_session(key, salt, account)
		record = Account.get(account).employees.get(key.first)
		record if record && record.authenticatable_salt == salt
	end

	def authorized? params
		self.role.has_permission? params
	end

	property :firstName, String, :default => ""
	property :lastName, String, :default => ""
	property :email, String, :default => ""
	property :encrypted_password, String, :default => ""
	property :pharmacies, [String]
	property :role_id
	property :account_id, String

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :set_account
	before_action :set_employee, only: [:show, :edit, :update, :destroy]
	# GET /employees
	# GET /employees.json
	def index
		@employees = @account.employees.all
		authorize Employee
	end

	# GET /employees/1
	# GET /employees/1.json
	def show
	end

	# GET /employees/new
	def new
		@employee = @account.employees.new
	end

	# GET /employees/1/edit
	def edit
	end

	# POST /employees
	# POST /employees.json
	def create
		@employee = @account.employees.new(employee_params)
		@employee.account_id=current_account.id
		respond_to do |format|
			if @employee.save
				format.html { render :new}
				format.json { render :json =>
					{
						:result => 1
					}.to_json
				}
				#format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
				#format.json { render :show, status: :created, location: @employee }
			else
				format.html { render :new }
				format.json { render json: @employee.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /employees/1
	# PATCH/PUT /employees/1.json
	def update
		respond_to do |format|
			if @employee.update_attributes(employee_params)
				format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
				format.json { render :show, status: :ok, location: @employee }
			else
				format.html { render :edit }
				format.json { render json: @employee.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /employees/1
	# DELETE /employees/1.json
	def destroy
		@employee.destroy
		respond_to do |format|
			format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_employee
		@employee = @account.employees.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def employee_params
		params.require(:employee).permit(:firstName, :lastName, :email, :password, :role_id, :pharmacies => []  )

	end
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
      <%= f.password_field :password, autocomplete: "off" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<%= react_component('ItemsList',
                      type:'employees',
                      urls: {'item':'/employees/search.json','filter':'/employees/info.json'},
                      filters:[
                        {'name':'company','label':'Select company','type':'select','multiple':true},
                        {'name':'price','type':'range'}
                      ],
                      headers:['Name','Email','Role'],
                      keys:['commercial_name','company','price'],simple:true,actionbar:true,
                      actions:['edit','delete','deactivate']
                    ) %>

app/views/employees/new.html.erb
<h2 class="ui header">Add New Employee</h2>
<div class="ui divider"></div>
<div class="add-form">
  <%= react_component('AddEditEmployee', url: '/employees.json', type: 'add',
  fields:[
    {'name':'firstName','type':'text','label':'First Name',subType:'text'},
    {'name':'lastName','type':'text','label':'Last Name',subType:'text'},
    {'name':'email','type':'text','label':'Email',subType:'email'},
    {'name':'password','type':'text','label':'Password',subType:'password'},
    {'name':'pharmacies','type':'select','label':'Select Pharmacies',multiple:true,'optionsUrl':"/roles.json"},
    {'name':'role_id','type':'select','label':'Select Employee Role','optionsUrl':"/pharmacies.json"}
  ])%>
</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @employee.firstName %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @employee.lastName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>
<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>