config/routes.rb
Rails.application.routes.draw do

  resources :roles
	constraints(Subdomain) do
		resources :pharmacies do
  		collection do
  			get 'search'
  		end
  	end
		devise_for :employees
		resources :employees
		resources :clients
		resources :suppliers
		resources :account_drugs
    resources :initial_balances
    resources :inventories
	end
	resources :drugs do
		collection do
			get 'search'
			get 'info'
      get 'alternatives'
		end
	end

	get 'home' => 'home#index'
	devise_for :accounts, :controllers => {:registrations => "accounts"}

	root 'home#index'

end

app/models/initial_balance.rb
class InitialBalance < CouchRest::Model::Base
  proxied_by :account
  design do
    view :by_account_id_and_id,
    :map => "function(doc) {
          if (doc.account_id) {
            emit([doc._id,doc.account_id], 1)
          }
        }",
    :reduce => "_sum"
  end


  validates :drug_id,presence: true
  validates :drug_id,:qunatity,numericality: { only_integer: true }
  validate :check_inventory_exists
  validate :check_drug_exists

  def check_inventory_exists
      inventory=@account.inventories.by_name.key(inventory_name)
      if inventory.count <= 0
        errors.add(:inventory_id, "invalid inventory")
      end
  end

  def check_drug_exists
      drug=@account.account_drugs.by_drug_id.key(drug_id)
      if drug.count <= 0
        drug=Drug.by_drug_id.key("#{drug_id}")
        if drug.count <= 0
          errors.add(:drug_id, "invalid drug")
        end
      end
  end

  #Model Properties
  property :drug_id, Integer
  property :location_layout, String
  property :qunatity, Integer
  property :inventory_name, String
  property :account_id, String
  property :date_time, String

end

app/controllers/initial_balances_controller.rb
class InitialBalancesController < ApplicationController
  before_action :set_account
  before_action :set_initial_balance, only: [:show, :edit, :update, :destroy]

  # GET /initial_balances
  # GET /initial_balances.json
  def index
    @initial_balances = @account.initial_balances.all
  end

  # GET /initial_balances/1
  # GET /initial_balances/1.json
  def show
  end

  # GET /initial_balances/new
  def new
    @initial_balance = @account.initial_balances.new
    @initial_balance.date_time=Time.now
  end

  # GET /initial_balances/1/edit
  def edit
  end

  # POST /initial_balances
  # POST /initial_balances.json
  def create
    @initial_balance = @account.initial_balances.new(initial_balance_params)
    @initial_balance.date_time=Time.now
    respond_to do |format|
      if @initial_balance.save
        format.html { redirect_to @initial_balance, notice: 'Initial balance was successfully created.' }
        format.json { render :show, status: :created, location: @initial_balance }
      else
        format.html { render :new }
        format.json { render json: @initial_balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /initial_balances/1
  # PATCH/PUT /initial_balances/1.json
  def update
    respond_to do |format|
      if @initial_balance.update(initial_balance_params)
        format.html { redirect_to @initial_balance, notice: 'Initial balance was successfully updated.' }
        format.json { render :show, status: :ok, location: @initial_balance }
      else
        format.html { render :edit }
        format.json { render json: @initial_balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initial_balances/1
  # DELETE /initial_balances/1.json
  def destroy
    @initial_balance.destroy
    respond_to do |format|
      format.html { redirect_to initial_balances_url, notice: 'Initial balance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_initial_balance
      @initial_balance = @account.initial_balances.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def initial_balance_params
      params.require(:initial_balance).permit(:drug_id, :location_layout, :inventory_name, :qunatity)
    end
end

app/helpers/initial_balances_helper.rb
module InitialBalancesHelper
end

app/views/initial_balances/_form.html.erb
<%= form_for(@initial_balance) do |f| %>
  <% if @initial_balance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@initial_balance.errors.count, "error") %> prohibited this initial_balance from being saved:</h2>

      <ul>
      <% @initial_balance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :drug_id %><br>
    <%= f.text_field :drug_id %>
  </div>
  <div class="field">
    <%= f.label :location_layout %><br>
    <%= f.text_field :location_layout %>
  </div>
  <div class="field">
    <%= f.label :inventory_name %><br>
    <%= f.text_field :inventory_name %>
  </div>
  <div class="field">
    <%= f.label :qunatity %><br>
    <%= f.text_field :qunatity %>
  </div>
  <div class="field">
    <%= f.label :date_time %><br>
    <label> <%= @initial_balance.date_time %></lable>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/initial_balances/edit.html.erb
<h1>Editing Initial Balance</h1>

<%= render 'form' %>

<%= link_to 'Show', @initial_balance %> |
<%= link_to 'Back', initial_balances_path %>

app/views/initial_balances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Initial Balances</h1>

<table>
  <thead>
    <tr>
      <th>Drug</th>
      <th>Location layout</th>
      <th>Inventory</th>
      <th>Qunatity</th>
      <th>Date time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @initial_balances.each do |initial_balance| %>
      <tr>
        <td><%= initial_balance.drug_id %></td>
        <td><%= initial_balance.location_layout %></td>
        <td><%= initial_balance.inventory_name %></td>
        <td><%= initial_balance.qunatity %></td>
        <td><%= initial_balance.date_time %></td>
        <td><%= link_to 'Show', initial_balance %></td>
        <td><%= link_to 'Edit', edit_initial_balance_path(initial_balance) %></td>
        <td><%= link_to 'Destroy', initial_balance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Initial balance', new_initial_balance_path %>

app/views/initial_balances/new.html.erb
<h1>New Initial Balance</h1>

<%= render 'form' %>

<%= link_to 'Back', initial_balances_path %>

app/views/initial_balances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Drug:</strong>
  <%= @initial_balance.drug_id %>
</p>

<p>
  <strong>Location layout:</strong>
  <%= @initial_balance.location_layout %>
</p>

<p>
  <strong>Inventory:</strong>
  <%= @initial_balance.inventory_name %>
</p>

<p>
  <strong>Qunatity:</strong>
  <%= @initial_balance.qunatity %>
</p>

<p>
  <strong>Date time:</strong>
  <%= @initial_balance.date_time %>
</p>

<%= link_to 'Edit', edit_initial_balance_path(@initial_balance) %> |
<%= link_to 'Back', initial_balances_path %>