config/routes.rb
Rails.application.routes.draw do

  resources :roles
	constraints(Subdomain) do
		resources :pharmacies do
  		collection do
  			get 'search'
  		end
  	end
		devise_for :employees
		resources :employees
		resources :clients
		resources :suppliers
		resources :account_drugs
    resources :initial_balances
    resources :inventories
	end
	resources :drugs do
		collection do
			get 'search'
			get 'info'
      get 'alternatives'
		end
	end

	get 'home' => 'home#index'
	devise_for :accounts, :controllers => {:registrations => "accounts"}

	root 'home#index'

end

app/models/role.rb
class Role < CouchRest::Model::Base
	use_database 'roles'
	design do
		view :by_name
	end
	property :name, String
	property :permissions

	validates :name, uniqueness: true
	validates :name, presence: true

	def has_permission?(options)
		self.permissions.has_key? options[:controller] and self.permissions[options[:controller]].include? options[:action]
	end

	def self.controllers_list(options = {})
		Rails.application.eager_load!
		result = ApplicationController.descendants.map(&:to_s)
		if options[:actions]
			controllers_actions = Hash.new
			ApplicationController.descendants.each do |c|
				controllers_actions.store c.to_s, c.action_methods.to_a if not c.to_s.include?'Devise'
			end
			result = controllers_actions
		end
		result
	end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	before_action :set_role, only: [:show, :edit, :update, :destroy]
	before_action :get_permissions, only: [:new, :edit]
	# GET /roles
	# GET /roles.json
	def index
		@roles = Role.all
	end

	# GET /roles/1
	# GET /roles/1.json
	def show
	end

	# GET /roles/new
	def new
		@role = Role.new
	end

	# GET /roles/1/edit
	def edit
	end

	# POST /roles
	# POST /roles.json
	def create
		@role = Role.new(role_params)

		respond_to do |format|
			if @role.save
				format.html { redirect_to @role, notice: 'Role was successfully created.' }
				format.json { render :show, status: :created, location: @role }
			else
				format.html { render :new }
				format.json { render json: @role.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /roles/1
	# PATCH/PUT /roles/1.json
	def update
		respond_to do |format|
			if @role.update(role_params)
				format.html { redirect_to @role, notice: 'Role was successfully updated.' }
				format.json { render :show, status: :ok, location: @role }
			else
				format.html { render :edit }
				format.json { render json: @role.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /roles/1
	# DELETE /roles/1.json
	def destroy
		@role.destroy
		respond_to do |format|
			format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_role
		@role = Role.find(params[:id])
	end

	def get_permissions
		@permissions = Role.controllers_list(actions: true)
	end
	# Never trust parameters from the scary internet, only allow the white list through.
	def role_params
		mapped_hash = Hash.new
		params[:role].try(:fetch, :permissions, {}).keys.each do |k|
			mapped_hash.store(k,[])
		end
		params.require(:role).permit(:name, :permissions => mapped_hash)
	end
end

app/helpers/roles_helper.rb
module RolesHelper
  def fields permissions
    arr = Array.new
    permissions.each do |controller,actions|

    end
    arr.push()
  end
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :permissions %><br>
    <% @permissions.each do |controller,actions|%>
      <%= controller.split(/(?<=[a-z])(?=[A-Z])/).first %>
      <br />
      <% actions.each do |action|%>
      <%= check_box_tag "role[permissions][#{controller}][]",action%>
      <%= f.label action %><br>
      <% end %>
    <% end%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>
<div class="ui divider"></div>
  <%= react_component('AddEditRoles', url: '/roles.json', type: 'edit',
  fields:[
    {name:'name',type:'text',label:'Role Name',subType:'text'},
    {name:'permissions',type:'group', subType:'selectGroup',options: @permissions, selectedOptions: @role.permissions},
  ]
  )%>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Roles</h1>


<%= react_component('ItemsList',
                      type:'roles',
                      urls: {'item':'/roles.json','filter':'/roles/info.json'},
                      filters:[
                        {'name':'company','label':'Select company','type':'select','multiple':true},
                        {'name':'price','type':'range'}
                      ],
                      headers:['Role'],
                      keys:['commercial_name','company','price'],simple:true,actionbar:true,
                      actions:['edit','delete']
                    ) %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h2 class="ui header">Add New Role</h2>
<div class="ui divider"></div>
  <%= react_component('AddEditRoles', url: '/roles.json', type: 'add',
  fields:[
    {name:'name',type:'text',label:'Role Name',subType:'text'},
    {name:'permissions',type:'group', subType:'selectGroup',options: @permissions},
  ]
  )%>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>