config/routes.rb
Rails.application.routes.draw do

  resources :roles
	constraints(Subdomain) do
		resources :pharmacies do
  		collection do
  			get 'search'
  		end
  	end
		devise_for :employees
		resources :employees
		resources :clients
		resources :suppliers
		resources :account_drugs
    resources :initial_balances
    resources :inventories
	end
	resources :drugs do
		collection do
			get 'search'
			get 'info'
      get 'alternatives'
		end
	end

	get 'home' => 'home#index'
	devise_for :accounts, :controllers => {:registrations => "accounts"}

	root 'home#index'

end

app/models/account_drug.rb
class AccountDrug < CouchRest::Model::Base
  proxied_by :account
  design do
    view :by_company
    view :by_account_id
    view :by_account_id_and_id,
    :map => "function(doc) {
          if (doc.account_id) {
            emit([doc._id,doc.account_id], 1)
          }
        }",
    :reduce => "_sum"
  end


  validates :drug_id,:arabic_name,:commercial_name,:international_barcode, presence: true
  validates :drug_id,:arabic_name,:commercial_name,:international_barcode, uniqueness: true
  validates :discount,:price,:no_meduim_units,:max_limit,:min_limit, numericality: true
  validates :drug_id, numericality: { only_integer: true }

  validate :check_barcode_uniqueness
  def check_barcode_uniqueness
      drug=Drug.by_international_barcode.key(international_barcode)
      if drug.count > 0
        errors.add(:international_barcode, "barcode already exist")
      end
  end
  #Model Properties
  property :drug_id, Integer
  property :arabic_name, String
  property :commercial_name, String
  property :international_barcode, String
  property :company, String
  property :price, String
  property :factor_form, String
  property :no_meduim_units, Float
  property :temperature, String
  property :scientific_name, String
  property :drug_type ,String
  property :discount, Float
  property :max_limit, Integer
  property :min_limit, Integer
  property :account_id, String
  property :layout_location, String

end

app/controllers/account_drugs_controller.rb
class AccountDrugsController < ApplicationController
	before_action :set_account
	before_action :set_account_drug, only: [:show, :edit, :update, :destroy]
	# GET /account_drugs
	# GET /account_drugs.json
	def index
		#byebug
		@account_drugs = @account.account_drugs.all

	end

	# GET /account_drugs/1
	# GET /account_drugs/1.json
	def show
	end

	# GET /account_drugs/new
	def new
		@account_drug = @account.account_drugs.new
	end

	# GET /account_drugs/1/edit
	def edit
	end

	# POST /account_drugs
	# POST /account_drugs.json
	def create
		@account_drug = @account.account_drugs.new(account_drug_params)
		@account_drug.price=formateNumber(@account_drug.price)
		@operation=@account.account_operations.new(:operation=>"add",:drug_id=>@account_drug.drug_id);
		@operation.save
		respond_to do |format|
			if @account_drug.save
				format.html { redirect_to @account_drug, notice: 'Account drug was successfully created.' }
				format.json { render :show, status: :created, location: @account_drug }
			else
				format.html { render :new }
				format.json { render json: @account_drug.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /account_drugs/1
	# PATCH/PUT /account_drugs/1.json
	def update
		respond_to do |format|
			result=@account_drug.update_attributes(account_drug_params)
			if result
				format.html { redirect_to @account_drug, notice: 'Account drug was successfully updated.' }
				format.json { render :show, status: :ok, location: @account_drug }
			else
				format.html { render :edit }
				format.json { render json: @account_drug.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /account_drugs/1
	# DELETE /account_drugs/1.json
	def destroy
		# Task DRUGBASE-64
		#@account_drug = @account.account_drugs.find("2aa2a903c9cb17c86dab25f77cbc27c5")
		#if @account_drug == nil
			#@operation=@account.account_operations.new(:operation=>"delete",:drug_id=>Drug.find("2aa2a903c9cb17c86dab25f77cbc27c5").drug_id);
			#@operation.save
		#end
		@account.account_operations.by_drug_id.key(@account_drug.drug_id).first.destroy
		@account_drug.destroy
		respond_to do |format|
			format.html { redirect_to account_drugs_url, notice: 'Account drug was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_account_drug
		@account_drug = @account.account_drugs.find(params[:id])
		if @account_drug == nil
			#@account_drug=Drug.find(params[:id])
			@account_drug=@account.account_drugs.new(Drug.find(params[:id]))
		end
	end
	# Use callbacks to share common setup or constraints between actions.


	# Never trust parameters from the scary internet, only allow the white list through.
	def account_drug_params
		params.require(:account_drug).permit(:drug_id, :arabic_name, :commercial_name, :international_barcode, :company, :price, :factor_form, :no_meduim_units, :temperature, :scientific_name, :drug_type, :discount, :min_limit, :max_limit,:layout_location)
	end
end

app/helpers/account_drugs_helper.rb
module AccountDrugsHelper
end

app/views/account_drugs/_form.html.erb
<%= form_for(@account_drug) do |f| %>
  <% if @account_drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_drug.errors.count, "error") %> prohibited this account_drug from being saved:</h2>

      <ul>
      <% @account_drug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Drug ID</label></br>
    <%= f.text_field :drug_id %>
  </div>
  <div class="field">
    <%= f.label :arabic_name %><br>
    <%= f.text_field :arabic_name %>
  </div>
  <div class="field">
    <%= f.label :commercial_name %><br>
    <%= f.text_field :commercial_name %>
  </div>
  <div class="field">
    <%= f.label :international_barcode %><br>
    <%= f.text_field :international_barcode %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :factor_form %><br>
    <%= f.text_field :factor_form %>
  </div>
  <div class="field">
    <%= f.label :no_meduim_units %><br>
    <%= f.text_field :no_meduim_units %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :scientific_name %><br>
    <%= f.text_field :scientific_name %>
  </div>
  <div class="field">
    <%= f.label :drug_type %><br>
    <%= f.text_field :drug_type %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.text_field :discount %>
  </div>
  <div class="field">
    <%= f.label :min_limit %><br>
    <%= f.text_field :min_limit %>
  </div>
  <div class="field">
    <%= f.label :max_limit %><br>
    <%= f.text_field :max_limit %>
  </div>
  <div class="field">
    <%= f.label :layout_location %><br>
    <%= f.text_field :layout_location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/account_drugs/edit.html.erb
<h1>Editing Account Drug</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_drug %> |
<%= link_to 'Back', account_drugs_path %>

app/views/account_drugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Account Drugs</h1>

<table>
  <thead>
    <tr>
      <th>Drug</th>
      <th>Arabic name</th>
      <th>Commercial name</th>
      <th>International barcode</th>
      <th>Company</th>
      <th>Price</th>
      <th>Factor form</th>
      <th>No meduim units</th>
      <th>Temperature</th>
      <th>Scientific name</th>
      <th>Drug type</th>
      <th>Discount</th>
      <th>Min limit</th>
      <th>Max limit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_drugs.each do |account_drug| %>
      <tr>
        <td><%= account_drug.drug_id %></td>
        <td><%= account_drug.arabic_name %></td>
        <td><%= account_drug.commercial_name %></td>
        <td><%= account_drug.international_barcode %></td>
        <td><%= account_drug.company %></td>
        <td><%= account_drug.price %></td>
        <td><%= account_drug.factor_form %></td>
        <td><%= account_drug.no_meduim_units %></td>
        <td><%= account_drug.temperature %></td>
        <td><%= account_drug.scientific_name %></td>
        <td><%= account_drug.drug_type %></td>
        <td><%= account_drug.discount %></td>
        <td><%= account_drug.min_limit %></td>
        <td><%= account_drug.max_limit %></td>
        <td><%= link_to 'Show', account_drug %></td>
        <td><%= link_to 'Edit', edit_account_drug_path(account_drug) %></td>
        <td><%= link_to 'Destroy', account_drug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account drug', new_account_drug_path %>

app/views/account_drugs/new.html.erb
<h1>New Account Drug</h1>

<%= render 'form' %>

<%= link_to 'Back', account_drugs_path %>

app/views/account_drugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Drug:</strong>
  <%= @account_drug.drug_id %>
</p>

<p>
  <strong>Arabic name:</strong>
  <%= @account_drug.arabic_name %>
</p>

<p>
  <strong>Commercial name:</strong>
  <%= @account_drug.commercial_name %>
</p>

<p>
  <strong>International barcode:</strong>
  <%= @account_drug.international_barcode %>
</p>

<p>
  <strong>Company:</strong>
  <%= @account_drug.company %>
</p>

<p>
  <strong>Price:</strong>
  <%= @account_drug.price %>
</p>

<p>
  <strong>Factor form:</strong>
  <%= @account_drug.factor_form %>
</p>

<p>
  <strong>No meduim units:</strong>
  <%= @account_drug.no_meduim_units %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @account_drug.temperature %>
</p>

<p>
  <strong>Scientific name:</strong>
  <%= @account_drug.scientific_name %>
</p>

<p>
  <strong>Drug type:</strong>
  <%= @account_drug.drug_type %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @account_drug.discount %>
</p>

<p>
  <strong>Min limit:</strong>
  <%= @account_drug.min_limit %>
</p>

<p>
  <strong>Max limit:</strong>
  <%= @account_drug.max_limit %>
</p>

<p>
  <strong>Layout Location:</strong>
  <%= @account_drug.layout_location %>
</p>

<%= link_to 'Edit', edit_account_drug_path(@account_drug) %> |
<%= link_to 'Back', account_drugs_path %>